# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frame_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(767, 569)
        MainWindow.setStyleSheet("QMainWindow\n"
"{\n"
"    background-color: #000046\n"
"}\n"
"\n"
"\n"
"QWidget\n"
"{\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLable\n"
"{\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    background-color: Black;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    min-width: 40ex;\n"
"    min-height: 10ex;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(252, 70, 107, 255), stop:1 rgba(63, 94, 251, 255));\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    min-width: 40ex;\n"
"    min-height: 10ex;\n"
"}\n"
"\n"
"QRadioButton\n"
"{\n"
"    color: white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 20, 598, 456))
        self.tabWidget.setStyleSheet("QTabWidget::pane\n"
"{\n"
"    border: 1px;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(142, 45, 226, 255), stop:1 rgba(74, 0, 224, 255))\n"
"}\n"
"\n"
"QTabBar::tab\n"
"{\n"
"    background:  rgba(74, 0, 224, 255);\n"
"    min-width: 40ex;\n"
"    min-height: 10ex;\n"
"    margin-left: 5px;\n"
"    margin-bottom: 10px;\n"
"    border-radius: 10px;\n"
"    left: -5px;\n"
"    color: white\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    background: rgba(142, 45, 226, 255)\n"
"}\n"
"\n"
"QLabel\n"
"{\n"
"    color: black;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.WeatherTab = QtWidgets.QWidget()
        self.WeatherTab.setObjectName("WeatherTab")
        self.city_nameLabel = QtWidgets.QLabel(self.WeatherTab)
        self.city_nameLabel.setGeometry(QtCore.QRect(20, 60, 549, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.city_nameLabel.setFont(font)
        self.city_nameLabel.setObjectName("city_nameLabel")
        self.degreesLabel = QtWidgets.QLabel(self.WeatherTab)
        self.degreesLabel.setGeometry(QtCore.QRect(30, 90, 261, 111))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.degreesLabel.setFont(font)
        self.degreesLabel.setObjectName("degreesLabel")
        self.weather_typeLabel = QtWidgets.QLabel(self.WeatherTab)
        self.weather_typeLabel.setGeometry(QtCore.QRect(330, 110, 545, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.weather_typeLabel.setFont(font)
        self.weather_typeLabel.setObjectName("weather_typeLabel")
        self.feels_likeLabel = QtWidgets.QLabel(self.WeatherTab)
        self.feels_likeLabel.setGeometry(QtCore.QRect(330, 130, 545, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.feels_likeLabel.setFont(font)
        self.feels_likeLabel.setObjectName("feels_likeLabel")
        self.Image = QtWidgets.QLabel(self.WeatherTab)
        self.Image.setGeometry(QtCore.QRect(250, 100, 71, 71))
        self.Image.setScaledContents(True)
        self.Image.setObjectName("Image")
        self.favouriteButton = QtWidgets.QPushButton(self.WeatherTab)
        self.favouriteButton.setGeometry(QtCore.QRect(310, 370, 271, 30))
        self.favouriteButton.setObjectName("favouriteButton")
        self.city_nameLine = QtWidgets.QLineEdit(self.WeatherTab)
        self.city_nameLine.setGeometry(QtCore.QRect(20, 30, 423, 31))
        self.city_nameLine.setStyleSheet("QLineEdit\n"
"{\n"
"    border-radius: 5px;\n"
"}")
        self.city_nameLine.setObjectName("city_nameLine")
        self.searchButton = QtWidgets.QPushButton(self.WeatherTab)
        self.searchButton.setGeometry(QtCore.QRect(451, 30, 120, 30))
        self.searchButton.setObjectName("searchButton")
        self.gridLayoutWidget = QtWidgets.QWidget(self.WeatherTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 180, 471, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.wind_speedLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.wind_speedLabel.setFont(font)
        self.wind_speedLabel.setObjectName("wind_speedLabel")
        self.gridLayout.addWidget(self.wind_speedLabel, 1, 0, 1, 1)
        self.humidityLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.humidityLabel.setFont(font)
        self.humidityLabel.setObjectName("humidityLabel")
        self.gridLayout.addWidget(self.humidityLabel, 0, 0, 1, 1)
        self.visibilityLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.visibilityLabel.setFont(font)
        self.visibilityLabel.setObjectName("visibilityLabel")
        self.gridLayout.addWidget(self.visibilityLabel, 2, 0, 1, 1)
        self.pressureLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pressureLabel.setFont(font)
        self.pressureLabel.setObjectName("pressureLabel")
        self.gridLayout.addWidget(self.pressureLabel, 3, 0, 1, 1)
        self.wind_speedImage = QtWidgets.QLabel(self.WeatherTab)
        self.wind_speedImage.setGeometry(QtCore.QRect(10, 240, 41, 41))
        self.wind_speedImage.setScaledContents(True)
        self.wind_speedImage.setObjectName("wind_speedImage")
        self.visibilityImage = QtWidgets.QLabel(self.WeatherTab)
        self.visibilityImage.setGeometry(QtCore.QRect(10, 300, 41, 41))
        self.visibilityImage.setScaledContents(True)
        self.visibilityImage.setObjectName("visibilityImage")
        self.pressureImage = QtWidgets.QLabel(self.WeatherTab)
        self.pressureImage.setGeometry(QtCore.QRect(10, 360, 41, 41))
        self.pressureImage.setScaledContents(True)
        self.pressureImage.setObjectName("pressureImage")
        self.humidityImage = QtWidgets.QLabel(self.WeatherTab)
        self.humidityImage.setGeometry(QtCore.QRect(10, 190, 41, 41))
        self.humidityImage.setScaledContents(True)
        self.humidityImage.setObjectName("humidityImage")
        self.tabWidget.addTab(self.WeatherTab, "")
        self.InfoTab = QtWidgets.QWidget()
        self.InfoTab.setObjectName("InfoTab")
        self.sunriseLabel = QtWidgets.QLabel(self.InfoTab)
        self.sunriseLabel.setGeometry(QtCore.QRect(10, 20, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sunriseLabel.setFont(font)
        self.sunriseLabel.setObjectName("sunriseLabel")
        self.sunsetLabel = QtWidgets.QLabel(self.InfoTab)
        self.sunsetLabel.setGeometry(QtCore.QRect(10, 60, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sunsetLabel.setFont(font)
        self.sunsetLabel.setObjectName("sunsetLabel")
        self.tabWidget.addTab(self.InfoTab, "")
        self.FavoritesTab = QtWidgets.QWidget()
        self.FavoritesTab.setObjectName("FavoritesTab")
        self.tabWidget.addTab(self.FavoritesTab, "")
        self.CustomTab = QtWidgets.QWidget()
        self.CustomTab.setObjectName("CustomTab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.CustomTab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 160, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.celsius_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.celsius_radioButton.setObjectName("celsius_radioButton")
        self.verticalLayout_2.addWidget(self.celsius_radioButton)
        self.fahrenheit_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.fahrenheit_radioButton.setObjectName("fahrenheit_radioButton")
        self.verticalLayout_2.addWidget(self.fahrenheit_radioButton)
        self.kelvin_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.kelvin_radioButton.setObjectName("kelvin_radioButton")
        self.verticalLayout_2.addWidget(self.kelvin_radioButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.CustomTab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(190, 30, 381, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.background_colorButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.background_colorButton.setObjectName("background_colorButton")
        self.verticalLayout_3.addWidget(self.background_colorButton)
        self.colorButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.colorButton.setObjectName("colorButton")
        self.verticalLayout_3.addWidget(self.colorButton)
        self.fontButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.fontButton.setObjectName("fontButton")
        self.verticalLayout_3.addWidget(self.fontButton)
        self.font_colorButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.font_colorButton.setObjectName("font_colorButton")
        self.verticalLayout_3.addWidget(self.font_colorButton)
        self.load_iconsButton = QtWidgets.QPushButton(self.CustomTab)
        self.load_iconsButton.setGeometry(QtCore.QRect(390, 290, 181, 30))
        self.load_iconsButton.setObjectName("load_iconsButton")
        self.save_styleButton = QtWidgets.QPushButton(self.CustomTab)
        self.save_styleButton.setGeometry(QtCore.QRect(390, 330, 181, 30))
        self.save_styleButton.setObjectName("save_styleButton")
        self.tabWidget.addTab(self.CustomTab, "")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 10, 621, 481))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(15, 12, 41, 255), stop:0.492537 rgba(48, 43, 99, 255), stop:1 rgba(36, 36, 62, 255));\n"
"    border-radius: 15px\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 0, 641, 501))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(142, 45, 226, 255), stop:1 rgba(74, 0, 224, 255));\n"
"    border-radius: 15px\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_2.raise_()
        self.frame.raise_()
        self.tabWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.city_nameLabel.setText(_translate("MainWindow", "В городе сейчас"))
        self.degreesLabel.setText(_translate("MainWindow", "15*"))
        self.weather_typeLabel.setText(_translate("MainWindow", "Облачно"))
        self.feels_likeLabel.setText(_translate("MainWindow", "Ощущается как"))
        self.Image.setText(_translate("MainWindow", "Рисунок"))
        self.favouriteButton.setText(_translate("MainWindow", "Добавить в избранное"))
        self.searchButton.setText(_translate("MainWindow", "Найти город"))
        self.wind_speedLabel.setText(_translate("MainWindow", "Скорость ветра"))
        self.humidityLabel.setText(_translate("MainWindow", "Влажность воздуха"))
        self.visibilityLabel.setText(_translate("MainWindow", "Видимость"))
        self.pressureLabel.setText(_translate("MainWindow", "Давление"))
        self.wind_speedImage.setText(_translate("MainWindow", "Ветер"))
        self.visibilityImage.setText(_translate("MainWindow", "Глаз"))
        self.pressureImage.setText(_translate("MainWindow", "Давл"))
        self.humidityImage.setText(_translate("MainWindow", "Капелька"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.WeatherTab), _translate("MainWindow", "Погода"))
        self.sunriseLabel.setText(_translate("MainWindow", "23562 seth"))
        self.sunsetLabel.setText(_translate("MainWindow", "23562 seth"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.InfoTab), _translate("MainWindow", "Доп. Информация"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FavoritesTab), _translate("MainWindow", "Избранное"))
        self.celsius_radioButton.setText(_translate("MainWindow", "Градусы Цельсия"))
        self.fahrenheit_radioButton.setText(_translate("MainWindow", "Градусы Фаренгейта"))
        self.kelvin_radioButton.setText(_translate("MainWindow", "Градусы Кельвина"))
        self.background_colorButton.setText(_translate("MainWindow", "Выбрать цвет фона"))
        self.colorButton.setText(_translate("MainWindow", "Выбрать цвет кнопок"))
        self.fontButton.setText(_translate("MainWindow", "Выбрать шрифт"))
        self.font_colorButton.setText(_translate("MainWindow", "Выбрать цвет текста"))
        self.load_iconsButton.setText(_translate("MainWindow", "Загрузить иконки"))
        self.save_styleButton.setText(_translate("MainWindow", "Сохранить стиль"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CustomTab), _translate("MainWindow", "Кастомизация"))
